# Generated by Django 4.1.3 on 2022-11-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Collection',
        ),
    ]
