# Generated by Django 4.1.3 on 2022-11-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
        ),
    ]
