# Generated by Django 4.1.3 on 2022-11-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
