# Generated by Django 4.1.3 on 2022-11-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_taggeditem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
